# Generated by Django 5.0.1 on 2025-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='access',
            field=models.CharField(default='user', max_length=5),
        ),
    ]
