# Generated by Django 5.0.1 on 2025-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0003_concertmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concertname', models.CharField(max_length=20)),
                ('ticketprice', models.IntegerField()),
                ('bookedtickets', models.IntegerField()),
            ],
        ),
    ]
