# Generated by Django 5.0.1 on 2025-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0004_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='useremail',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='username',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
