# Generated by Django 5.0.1 on 2025-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertapp', '0006_alter_ticketbooking_totalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticketprice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
